import type { Metadata } from "next";
import { ThemeProvider } from "@/context/ThemeContext";

import "./globals.css";
import ErrorBoundary from "@/components/ErrorBoundary";

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
      >
        <ThemeProvider>
          <ErrorBoundary fallback={<div>Something went wrong!</div>}>
            
              

              {children}
            
          </ErrorBoundary>
        </ThemeProvider>
      </body>
    </html>
  );
}
