import type { Metadata } from "next";
import { ThemeProvider } from "@/context/ThemeContext";

import "./globals.css";
import ErrorBoundary from "../components/atoms/ErrorBoundary";

import { FontProvider } from "@/context/FontContext";

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider><FontProvider>
          <ErrorBoundary fallback={<div>Something went wrong!</div>}>
            <div className="min-h-screen flex flex-col">{children}</div>
            
          </ErrorBoundary></FontProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
